name: demo_image_builder

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  # push:
  #  branches:
  #   - main
  # pull_request:
  # Allow mannually trigger 
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      ENV_VM_RESOUCE_GROUPE : demo_image_builder
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create resoucegroup
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          echo "Create ResourceGroup"
          az group create -n ${{ env.ENV_VM_RESOUCE_GROUPE }} -l eastus

    # https://github.com/Azure/build-vm-image
    - name: Build and Distribute Custom VM Image
      id: build-image-id
      uses: azure/build-vm-image@v0
      with: 
        resource-group-name: ${{ env.ENV_VM_RESOUCE_GROUPE }}
        location: 'eastus'
        managed-identity: 'image-builder-m-id'
        source-os-type: 'linux'
        source-image-type: 'PlatformImage'
        source-image: 'Canonical:0001-com-ubuntu-server-focal:20_04-lts:latest'
        dist-resource-id: /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ env.ENV_VM_RESOUCE_GROUPE }}/providers/Microsoft.Compute/images/my-ubunutu2004nginx-${{ GITHUB.RUN_NUMBER }}
        customizer-source: ${{ GITHUB.WORKSPACE }}/html
        customizer-script: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get -y install nginx git
          sudo systemctl enable nginx
          sudo cp -r /tmp/html /var/www/

    - name: Create vm
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          echo "Create VM"
          az vm create --resource-group ${{ env.ENV_VM_RESOUCE_GROUPE }} \
          --name myVM-${{ GITHUB.RUN_NUMBER }} \
          --image ${{ steps.build-image-id.outputs.custom-image-uri }}  \
          --admin-username azureuser --generate-ssh-keys
          echo "Open VM Port"
          az vm open-port \
          --resource-group ${{ env.ENV_VM_RESOUCE_GROUPE }} \
          --name "myVM-${{ GITHUB.RUN_NUMBER }}" \
          --port 80
